# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_book',
                'doc_host': 'https://devalkyrie.github.io',
                'git_url': 'https://github.com/devalkyrie/nbdev_book',
                'lib_path': 'nbdev_book'},
  'syms': {'nbdev_book.core': {'nbdev_book.core.foo': ('core.html#foo', 'nbdev_book/core.py')}}}